eureka:
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:8761/eureka
      #       defaultZone: http://www.leesh.top:8761/eureka
      defaultZone: https://eureka.leesh.top/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
    hostname: LeePC
spring:
  application:
    name: clouds-config-server-lee
server:
  port: 8761